// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#ifndef __BINDINGS_MY_COMPONENT_H
#define __BINDINGS_MY_COMPONENT_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

typedef struct jco_testing_default_i_own_data_t {
  int32_t __handle;
} jco_testing_default_i_own_data_t;

typedef struct jco_testing_default_i_borrow_data_t {
  int32_t __handle;
} jco_testing_default_i_borrow_data_t;

typedef jco_testing_default_i_own_data_t my_component_own_data_t;

// Imported Functions from `jco-testing:default/I`
extern void jco_testing_default_i_method_data_f(jco_testing_default_i_borrow_data_t self);

// Exported Functions from `my-component`
my_component_own_data_t my_component_id(my_component_own_data_t x);

// Helper Functions

extern void jco_testing_default_i_data_drop_own(jco_testing_default_i_own_data_t handle);

extern jco_testing_default_i_borrow_data_t jco_testing_default_i_borrow_data(jco_testing_default_i_own_data_t handle);


#ifdef __cplusplus
}
#endif
#endif
