// Generated by `wit-bindgen` 0.34.0. DO NOT EDIT!
#include "my_component.h"
#include <stdlib.h>

// Imported Functions from `jco-testing:default/I`

__attribute__((__import_module__("jco-testing:default/I"), __import_name__("[method]data.f")))
extern void __wasm_import_jco_testing_default_i_method_data_f(int32_t);

// Exported Functions from `my-component`


// Canonical ABI intrinsics

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

__attribute__((__import_module__("jco-testing:default/I"), __import_name__("[resource-drop]data")))
extern void __wasm_import_jco_testing_default_i_data_drop(int32_t handle);

void jco_testing_default_i_data_drop_own(jco_testing_default_i_own_data_t handle) {
  __wasm_import_jco_testing_default_i_data_drop(handle.__handle);
}

jco_testing_default_i_borrow_data_t jco_testing_default_i_borrow_data(jco_testing_default_i_own_data_t arg) {
  return (jco_testing_default_i_borrow_data_t) { arg.__handle };
}

// Component Adapters

void jco_testing_default_i_method_data_f(jco_testing_default_i_borrow_data_t self) {
  __wasm_import_jco_testing_default_i_method_data_f((self).__handle);
}

__attribute__((__export_name__("id")))
int32_t __wasm_export_my_component_id(int32_t arg) {
  my_component_own_data_t ret = my_component_id((my_component_own_data_t) { arg });
  return (ret).__handle;
}

// Ensure that the *_component_type.o object is linked in

extern void __component_type_object_force_link_my_component(void);
void __component_type_object_force_link_my_component_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_my_component();
}
